name: Checks
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install deps
      run: |
        npm install
    - name: Hardhat Test
      run: |
        npx hardhat test
      env:
        # These are not needed for the tests but
        # hardhat fails to start if not present.
        NODE_TEST: "x"
        NODE_MAIN: "x"
        PRIVATE_KEY: "00000000000000000000000000000000000000000000000000"
        REPORT_GAS: "true"
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y make
          npm install -g solhint
      - name: Solhint
        run: |
          make solhint
  Security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends python3-pip python3-dev build-essential
          npm install hardhat
      - name: Slither Static Analysis
        run: |
          git clone https://github.com/crytic/slither.git && cd slither && sudo python3 setup.py install
          make slither
      - name: Echidna Mutating testing
        run: |
          pip3 install crytic-compile slither-analyzer
          wget https://github.com/crytic/echidna/releases/download/v1.7.0/echidna-test-1.7.0-Ubuntu-18.04.zip
          unzip echidna-test-1.7.0-Ubuntu-18.04.zip
          tar -xf echidna-test.tar.gz
          sudo mv ./echidna-test /usr/bin/
          make echidna
        env:
          # These are not needed for the tests but
          # hardhat fails to start if not present.
          NODE_TEST: "x"
          NODE_MAIN: "x"
          PRIVATE_KEY: "00000000000000000000000000000000000000000000000000"
          REPORT_GAS: "true"
